"""Generate AuthToken

Revision ID: f55199b2e3b1
Revises: 12f267467300
Create Date: 2022-12-04 15:48:02.919778

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f55199b2e3b1"
down_revision = "12f267467300"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_token",
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("key", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_token")
    # ### end Alembic commands ###
